### ISSUE TITLE
Create predictions from dataloader

### ISSUE THREAD

**Issue by raspstephan** [raspstephan/nwp-downscale#17]
Given a validation dataloader, create predictions in real units as an xarray dataset.

**Comment by raspstephan** [comment]
#21 adds functionality to do create predictions for a single lead time. 

Eventually, we want to extend this to multiply lead times which is also #18

**Comment by raspstephan** [comment]
@HirtM I wrote a train.py script. 

`python train.py -c configs/000-test.yml`

The prediction file is saved in `/datadrive/saved_models/`.

Note that the lat-lon dimensions aren't exactly the same as for MRMS because they have to be multiples of the raw TIGGE size.

**Comment by HirtM** [comment]
@raspstephan Great! The nc-file currently only has zeros in it, though. 
But I guess I could still use it for testing.

**Comment by raspstephan** [comment]
Ah yes, this happens when the network doesn't start training. I ran it again. The new file should have some positive values in it. I only trained for one epoch, so expect it to be pretty crap.
