### ISSUE TITLE
MRMS data sources

### ISSUE THREAD

**Issue by anna-allen** [raspstephan/nwp-downscale#25]
@raspstephan @HirtM which product should we use for the MRMS data?
It looks like availability of the different products is:

- MultiSensor: September 2020 onwards only
- RadarOnly: 1hr, 3hr and 6hr accumulations available from 28/09/2019
- RadarOnly: 1hr and 24hr accumulations from 2015 onward available at https://mtarchive.geol.iastate.edu/year/month/day/mrms/ncep/

There are also some MRMS reanalysis projects (e.g http://edc.occ-data.org/nexrad/mosaic/), however they don't include accumulations.

Is it ok to use RadarOnly or do we really need MultiSensor?

**Comment by raspstephan** [comment]
I wrote a download script for the new MRMS data. Data is currently downloading from 2018-2020. This will take a few days. Note that I have moved the data we had already downloaded to `/datadrive/mrms_old` on the CPU machine. Also @HirtM.
