### ISSUE TITLE
Prevent security issues on Azure VMs

### ISSUE THREAD

**Issue by raspstephan** [raspstephan/nwp-downscale#35]
I enabled Just in Time (JIT) access for our VMs to prevent the Azure security warnings. @annavaughan @HirtM Here is what you need to do to be able to log in.

In the Azure portal go to the security center. 

![image](https://user-images.githubusercontent.com/2786927/109625772-ffd16080-7b3f-11eb-8850-d0a8082171b0.png)

Then go to the Azure defender on the left and click the Just-in-time VM access button below.

![image](https://user-images.githubusercontent.com/2786927/109625951-37400d00-7b40-11eb-964d-d94d9837dc89.png)

Click on the VM you want to you and click request access.

![image](https://user-images.githubusercontent.com/2786927/109626028-50e15480-7b40-11eb-8c0e-9e037bd6fa23.png)

Here toggle the on button. My IP is fine. 3 hours is the maximum.

![image](https://user-images.githubusercontent.com/2786927/109626153-7c643f00-7b40-11eb-8224-58059200729e.png)

Then click request access. This takes a minute or so but then you should be able to log in like usual. Unfortunately, I guess you will have to do this every three hours again but let's hope this solves the problem.

**Comment by raspstephan** [comment]
Also, I guess we should shut down the VMs when we are not using them. So just make sure to save intermediate files, etc before shutting down.

**Comment by raspstephan** [comment]
Another related issue I am noticing is that my .ssh/id_rsa files keep disappearing after while, which is annoying because I need to set up a new Github access every time. Do any of you have the same issue?

**Comment by HirtM** [comment]
I think I've always entered my password, so no.

Quoting Stephan Rasp <notifications@github.com>:

> Another related issue I am noticing is that my .ssh/id_rsa files  
> keep disappearing after while, which is annoying because I need to  
> set up a new Github access every time. Do any of you have the same  
> issue?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/raspstephan/nwp-downscale/issues/35#issuecomment-789786325


-- 
Dr. Mirjam Hirt
LMU - Meteorological Institute Munich
Waves to Weather
Theresienstr. 37
80333 Munich, Germany
Tel.: +49 (0)89 2180 4677
Email: m.hirt@lmu.de
Website: https://www.meteo.physik.uni-muenchen.de/~M.Hirt/

**Comment by raspstephan** [comment]
JIT seems to have fixed that, so will close.
