### ISSUE TITLE
Switch to Azure

### ISSUE THREAD

**Issue by raspstephan** [raspstephan/nwp-downscale#4]
Set up 

- [x] Estimate how much storage we will need in the end.
- [x] Get everyone on the Azure grant
- [x] Set up a virtual machine
- [x] Set up Jupyter hub (for each user separately or just use separate repos?)
- [x] Setup VM with GPU

**Comment by raspstephan** [comment]
**Data size estimation.** 

The TIGGE ensemble will be the dominant one. For the CONUS-MRMS domain (250x500 grid pts), total precipitation for a single member for a single init and lead time takes as netcdf takes up 500K. I would assume that other variables take up more space because the data is less sparse but let's take 500K as an estimate.

Forecasts are initialized twice a day. MRMS data is available from September 2019 (roughly 15 months). 30*15*2 = 900 initializations.

We should probably download all 50 members if possible. 

HRRR is archived up to 24h lead time. I was so for unsuccessful in finding data download sites for HREF or HRRRE, but ideally we would go into day two, so let's take 48h lead / 6h = 8 time steps.

That makes 900 * 50 * 8 * 500K =180G for a single variable. If we then assume around 10 variables we have roughly 1.8T. Manageable but quite a lot still. Especially because it's very hard to feed that much data into the NN efficiently (at least for me...).

So how could we reduce the data volumes a little? Here are some thoughts. @HirtM, feel free to discuss and add your thoughts.

1) We might not need the entire MRMS domain. Just CONUS is enough. using lat=(25, 50) and lon=(235, 285) reduced the data amount by half = 90G per variable. For training we might even further crop the region to the Central US at first.

![image](https://user-images.githubusercontent.com/2786927/102012294-e2170b00-3d49-11eb-9e17-b8c6f54feb86.png)

2) We might not need all ensemble members for training. Maybe 10 (--> 18GB) would be enough. We could then download the full ensemble for a few time steps for evaluation. But maybe we will regret it. 


Next task. Figure out which Azure storage option we want and how much it costs.

**Comment by HirtM** [comment]
3. Would it be possible to save the data in e.g. single precision (if it is in double precision)? 

Regarding point 2: The ensemble only acts as "conditioner" in the GAN, right? So does the GAN learn more/faster/better when it has more different conditions for the same  radar image? I could imagine that the stochasticity might work better. But also, 10 ensemble members for the same radar image might be enough. Maybe I can find if there are guidelines on that.

**Comment by raspstephan** [comment]
> Would it be possible to save the data in e.g. single precision (if it is in double precision)?

It's already single precision I believe.

>  The ensemble only acts as "conditioner" in the GAN, right? So does the GAN learn more/faster/better when it has more different conditions for the same radar image? I could imagine that the stochasticity might work better.

That's exactly what I was thinking. If you look at the ensemble differences, they are small in terms of overall precip location. So I think this would be more like a data augmentation to prevent overfitting.

![image](https://user-images.githubusercontent.com/2786927/102203292-b1111480-3ec8-11eb-94c3-1ffd9a354cde.png)

**Comment by raspstephan** [comment]
@HirtM You should be added to the AI for Earth Community soon. I already added your Azure account to the grant. 

I just watched [this video](https://microsoft.sharepoint.com/teams/AIforEarthGranteeCommunity/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FAIforEarthGranteeCommunity%2FShared%20Documents%2FEvent%20Resources%2FSummit%20Resources%2F2020%20Jun%2025%20%2D%2026%2FAzure%20Core%20Services%2Emp4&parent=%2Fteams%2FAIforEarthGranteeCommunity%2FShared%20Documents%2FEvent%20Resources%2FSummit%20Resources%2F2020%20Jun%2025%20%2D%2026) on cloud computing which I found very helpful. Maybe once you've watched it (you might have to wait to be added to the community) we can set up a VM with a Jupyter Hub together. I will try to look up how to set up a jupyterhub in the meantime. 

I am not quite sure what the best way for us to collaborate will be (one VM or several? Storage on blobs?) but we can discuss that.

**Comment by raspstephan** [comment]
@HirtM You should have access now.

**Comment by HirtM** [comment]
@raspstephan I can sign in to the default directory on azure, but not the video link you gave me. That was somehow more complicated than I expected :D

**Comment by raspstephan** [comment]
@HirtM Can you log onto this website? https://microsoft.sharepoint.com/teams/AIforEarthGranteeCommunity/

**Comment by HirtM** [comment]
@raspstephan Now it worked (I had to open a new private browser window, I think, at least that solved it). I try to watch the video today, maybe tomorrow or on Friday we can try setting up the Jupyter hub?

**Comment by raspstephan** [comment]
@HirtM yes, let's do it. What time tomorrow, Friday, would work for you. I can do any time except 11:00-11:30.

**Comment by HirtM** [comment]
@raspstephan How about 15:00? But I am also available at other times.

**Comment by raspstephan** [comment]
I've been looking for JupyterHub guides. There is this one which includes Kubernetes which we don't need at the moment, I think. But the guide might still be useful: https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/index.html

Here is another guide we could look into: https://tljh.jupyter.org/en/latest/

**Comment by raspstephan** [comment]
@HirtM I think the issue was with a conflict  between the data-science VM Image and the littlest jupyterhub configs. 

For starters, there are a lot of different conda environments which could be a problem...
![image](https://user-images.githubusercontent.com/2786927/102638335-9e603f00-4157-11eb-8c33-7a7eeab7498c.png)

If I start a jupyterhub from the base environment I can log on but I don't see the admin button.

![image](https://user-images.githubusercontent.com/2786927/102641325-3102dd00-415c-11eb-876c-efd4bb30b569.png)

I think it might have to do with the fact that I started the jupyterhub without sodu. But `sudo jupyterhub` gives me `sudo: jupyterhub: command not found` which I think has to do what's in the super user path. Then it gets messy. 

So I think there are two options. 

1. We reinstall the littlest jupyterhub with just the vanilla ubuntu VM image
2. We use the data science image and follow the regular jupyterhub installation guide: https://jupyterhub.readthedocs.io/en/stable/installation-guide.html

I think I will try option 2 first because it might help me understand what is actually happening in the background. But I might start with a fresh VM.

**Comment by HirtM** [comment]
@raspstephan Sounds like a good plan! I am busy tomorrow, but maybe I have some time to look at it on Sunday. If you need help with something specific, let me know.

**Comment by raspstephan** [comment]
I think I set up a working JupyterHub for us to use. @HirtM I think the problem was that the [Data Science image](https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/dsvm-ubuntu-intro#jupyterhub-and-jupyterlab) already had a jupyterhub installed, so installing the littlest jupyterhub on top caused issues. But the great thing is that we can just use the one that is already there with a few minor modifications.

First, we need to make sure we all can use our own users and environments. This required the following change in `/etc/jupyterhub/jupyterhub_config.py`

```
c.Spawner.default_url = '/lab'
c.Spawner.notebook_dir = '~'
```

This first line makes sure that Jupyter Lab is started instead of the default tree view. The second line was originally set to `~/notebooks` and determines in which directory new notebooks are started. However, if `~/notebooks` doesn't exists (e.g. for a new user), this will cause an error. 

Now, we can each use our own environment. For this we need to create new unix users using `sudo useradd -m <username>`. You can log in using the root user `nwp-downscale` with the password I emailed you to do so. `-m` ensures that a home directory is created for the user. Then you can set a password using `sudo passwd <username>`.  It also makes sense (for sharing files) to make sure all users are in the same group. We can use the group `nwp-downscale` which is equivalent to `root`. To add your new user to the group do 
```
sudo usermod -a -G nwp-downscale <username>
sudo usermod -g nwp-downscale <username>
```
The second command makes this the primary group so that all files created by that user will automatically have the `root` group and everyone can read and write them.

Now you should be able to go to `https://<ip-address>:8000` and log in with your username and password to use JupyterLab. You can look up the IP address in the Azure portal but I also emailed it to you. When you do this for the first time, your browser will probably tell you that this is not safe. If you are on Chrome you need to click anywhere in the window and type `thisisunsafe`. No, this is not a joke.

I would also suggest that we use separate conda environments for now, right? For this you can just open a terminal from Jupyter or via ssh using your username and create a new environment with `conda create -n <name>`. Next, you need to at least do `conda install ipykernel` which allows the kernel to be found when starting a new notebook (you also need to reload the window). 

The current VM has 16GB RAM, 150GB local SSD storage and 4 CPUs. This isn't a lot and we can think about upgrading if necessary. But it's cheap, so we can keep it running continuously for now. 

Finally, we need to attach our data disk (currently a 1TB HDD). For this I followed [this guide](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/attach-disk-portal). I mounted the drive at  `/datadrive`. This is where we will save the data for now.

 @anna-184702, let me know if you have any questions.

**Comment by raspstephan** [comment]
@anna-184702 @HirtM I still haven't really figured out the best way to collaborate in science projects, so I am open to any suggestions. Here are some things I would start with. 

I think it's important that the `main` branch of the repository always stays functional and up-to date. To ensure that I think it would make sense if we all implement new code in a separate branch (unless it's just a small change) and then create a pull request into `main`. Then we can review whether this will break anything for the other users. I am not sure if this is overkill? 

One thing we should definitely avoid is that we are working with different code, i.e. that our branches diverge too much. So frequently merging into `main` and pulling the latest updates from `main` into our personal branches is crucial. 

I am not super sure how this works with notebooks since merging doesn't really work well for them. I like to number my notebooks so that I kind of know in which order I've worked on them. So maybe with notebooks we just have to talk to each other :)

In any case, notebooks go in the `notebooks` directory. All other code goes into the `src` directory which will eventually be a Python module (and can be renamed).

**Comment by HirtM** [comment]
@raspstephan  I successfully managed to create my user account and login. However it did not work the first time, when I used capital letters (M.Hirt) in my User name. There was some error message that said something about missing user directory for "m.hirt". I consequently tried changing my user account to small letters only and then it worked. 
@anna-184702 Try using small letters for your user account, perhaps it then works directly for you. (I am not sure though that that was really the problem.)

Thanks for the detailed instructions, Stephan!

**Comment by HirtM** [comment]
I am still figuring out the conda environment and packages. (By default, conda used python 3.9 and there seems to be an issue with cartopy.) @raspstephan Do you have an environment file you can share, so we are all using the same versions etc?

**Comment by HirtM** [comment]
> 
> 
> @anna-184702 @HirtM I still haven't really figured out the best way to collaborate in science projects, so I am open to any suggestions. Here are some things I would start with.
> 
> I think it's important that the `main` branch of the repository always stays functional and up-to date. To ensure that I think it would make sense if we all implement new code in a separate branch (unless it's just a small change) and then create a pull request into `main`. Then we can review whether this will break anything for the other users. I am not sure if this is overkill?
> 
> One thing we should definitely avoid is that we are working with different code, i.e. that our branches diverge too much. So frequently merging into `main` and pulling the latest updates from `main` into our personal branches is crucial.
> 
> I am not super sure how this works with notebooks since merging doesn't really work well for them. I like to number my notebooks so that I kind of know in which order I've worked on them. So maybe with notebooks we just have to talk to each other :)
> 
> In any case, notebooks go in the `notebooks` directory. All other code goes into the `src` directory which will eventually be a Python module (and can be renamed).

Sounds like a good plan! I don't have much experience with joint git repositories, to be honest. But this sounds reasonable for the beginning and we can always adapt our approach on the way.

**Comment by raspstephan** [comment]
> I am still figuring out the conda environment and packages. (By default, conda used python 3.9 and there seems to be an issue with cartopy.) @raspstephan Do you have an environment file you can share, so we are all using the same versions etc?

Yeah, I am also still struggling with the environments. I had to downgrade to Python 3.8. Also, sometimes I had to de- and reactivate my own environment to make it work and also restart my notebooks. I don't have a great environment file at the moment, I just installed a few packages. Maybe it would make sense to also use one of the root environments that everyone can use...

And btw, I did see somewhere that you have to use lower-case letters.

**Comment by anna-allen** [comment]
> @anna-184702 @HirtM I still haven't really figured out the best way to collaborate in science projects, so I am open to any suggestions. Here are some things I would start with.
> 
> I think it's important that the `main` branch of the repository always stays functional and up-to date. To ensure that I think it would make sense if we all implement new code in a separate branch (unless it's just a small change) and then create a pull request into `main`. Then we can review whether this will break anything for the other users. I am not sure if this is overkill?
> 
> One thing we should definitely avoid is that we are working with different code, i.e. that our branches diverge too much. So frequently merging into `main` and pulling the latest updates from `main` into our personal branches is crucial.
> 
> I am not super sure how this works with notebooks since merging doesn't really work well for them. I like to number my notebooks so that I kind of know in which order I've worked on them. So maybe with notebooks we just have to talk to each other :)
> 
> In any case, notebooks go in the `notebooks` directory. All other code goes into the `src` directory which will eventually be a Python module (and can be renamed).

@raspstephan sounds good to me!

**Comment by raspstephan** [comment]
Here are the steps I took to setup the GPU VM. Lots of things to automate if this turns out to be a common action.

```
lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
sudo parted /dev/sda --script mklabel gpt mkpart xfspart xfs 0% 100%
sudo mkfs.xfs /dev/sda1
sudo partprobe /dev/sda1
sudo mkdir /datadrive
sudo chmod a+w /datadrive
sudo mount /dev/sda1 /datadrive
sudo blkid  # Copy UUID
sudo vi /etc/fstab
# UUID=24229d55-fce4-4d85-96bb-e80d2d461ddc /datadrive   xfs   defaults,nofail   1   2

sudo useradd -m stephan
sudo passwd stephan
sudo usermod -a -G nwp-downscale stephan
sudo usermod -g nwp-downscale stephan

su stephan
ssh-keygen 
vi .ssh/id_rsa.pub 
git config --global user.name "raspstephan"
git config --global user.email "raspstephan@gmail.com"
git clone git@github.com:raspstephan/nwp-downscale.git

sudo vi //etc/jupyterhub/jupyterhub_config.py

sudo rm -r /anaconda/pkgs/typing_extensions-3.7.4.3* /anaconda/pkgs/python-dateutil-2.8.1* /anaconda/pkgs/async_generator-1.10*
conda env create -f /home/stephan/nwp-downscale/environment.yml -n nwp-downscale

sudo reboot


```

**Comment by HirtM** [comment]
Setting my account on the gpu: 
sudo useradd -m m.hirt
sudo passwd m.hirt
sudo usermod -a -G nwp-downscale m.hirt
sudo usermod -g nwp-downscale m.hirt

su m.hirt
cd
ssh-keygen
vi .ssh/id_rsa.pub 
git clone git@github.com:raspstephan/nwp-downscale.git
cd nwp-downscale 
git config user.name "m.hirt"
git config --global user.name "m.hirt"

**Comment by raspstephan** [comment]
Expanding disk space

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks

```
  504  brew update && brew install azure-cli
  505  az
  506  az login
  507  az disk list     --resource-group myResourceGroup     --query '[*].{Name:name,Gb:diskSizeGb,Tier:accountType}' \
  508  az disk list --resource-group nwp-downscale --query '[*].{Name:name,Gb:diskSizeGb,Tier:accountType}'
  509  az disk update     --resource-group myResourceGroup     --name myDataDisk \
  510  az disk update --resource-group nwp-downscale --name nwp-downscale_hdd --size-gb 3072
  511  az vm start --resource-group nwp-downscale --name nwp-downscale
  512  az vm show --resource-group nwp-downscale --name nwp-downscale -d --query [publicIps] --output tsv
```

On machine

```
lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
  230  sudo umount /dev/sdc1
  231  df -h
  232  sudo parted /dev/sdc
  234  lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
  240  sudo mount /dev/sdc1 /datadrive
  241  sudo xfs_growfs -d /dev/sdc1
  242  df -h
```

**Comment by raspstephan** [comment]
To set up the second (and more) GPU VM

```
lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
sudo parted /dev/sda --script mklabel gpt mkpart xfspart xfs 0% 100%
sudo mkfs.xfs /dev/sda1
sudo partprobe /dev/sda1
sudo mkdir /datadrive_ssd
sudo chmod a+w /datadrive_ssd
sudo mount /dev/sda1 /datadrive_ssd
sudo blkid  # Copy UUID
sudo vi /etc/fstab
# UUID=24229d55-fce4-4d85-96bb-e80d2d461ddc /datadrive_ssd   xfs   defaults,nofail   1   2

sudo useradd -m stephan
sudo passwd stephan
sudo usermod -a -G nwp-downscale stephan
sudo usermod -g nwp-downscale stephan

sudo vi //etc/jupyterhub/jupyterhub_config.py
# c.Spawner.default_url = '/lab'
# c.Spawner.notebook_dir = '~'

su stephan
ssh-keygen 
vi .ssh/id_rsa.pub 
git config --global user.name "raspstephan"
git config --global user.email "raspstephan@gmail.com"
git clone https://github.com/raspstephan/nwp-downscale.git

sudo reboot

# Log in again
# Add IP to JIT on primary GPU
sudo rsync -vra nwp-downscale@<gpu-ip>:/datadrive_ssd/ /datadrive_ssd/

sudo rm -r /anaconda/pkgs/typing_extensions-3.7.4.3* /anaconda/pkgs/python-dateutil-2.8.1* /anaconda/pkgs/async_generator-1.10*
conda env create -f /home/stephan/nwp-downscale/environment.yml -n nwp-downscale

```

**Comment by raspstephan** [comment]
Not quite sure what exactly I did to make this work on the GPU2 VM. But something following this: https://ipywidgets.readthedocs.io/en/stable/user_install.html

But I also did this: https://askubuntu.com/questions/786272/why-does-installing-node-6-x-on-ubuntu-16-04-actually-install-node-4-2-6#786279

But collapsable headings, etc still doesn't work. Only tqdm.notebook and xarray.
