### ISSUE TITLE
PyTorch or Tensorflow

### ISSUE THREAD

**Issue by HirtM** [raspstephan/nwp-downscale#7]
We have to decide on whether to use PyTorch or Tensorflow. 
I have started a coursera course on GANs, there they use **PyTorch** and motivate it by [this article](https://thegradient.pub/state-of-ml-frameworks-2019-pytorch-dominates-research-tensorflow-dominates-industry/),  which suggests it is the better tool for research. Of course, the article might already be outdated (it's from 2019).

**Comment by raspstephan** [comment]
@anna-184702 will have an opinion on this :) 
(But TF isn't so bad either any more 😄 )

**Comment by raspstephan** [comment]
@HirtM There is also this Coursera course on GANs: https://www.coursera.org/specializations/generative-adversarial-networks-gans

No idea if it's any good though. They also use PyTorch I think. I might have a look at it to refresh my knowledge.

**Comment by anna-allen** [comment]
My vote is definitely PyTorch 😁

**Comment by HirtM** [comment]
So I guess it's Pytorch for now...
