### ISSUE TITLE
Let's use a joint conda environment

### ISSUE THREAD

**Issue by HirtM** [raspstephan/nwp-downscale#8]
- [x] Make a joint conda environment for everyone to use with all the important packages installed 

I already copied the py37_pytorch environment and added xarray, cartopy, netcdf4 and that seems to work well so far. 
Now I just need to do that with sudo permissions, I assume so that everyone can access it.

**Comment by raspstephan** [comment]
Absolutely agree. Most importantly, we should maintain a environment.yml file in the repo so we can quickly recreate out conda environment if we move to a new machine.

Is there a way to make our new conda environment the default when logging into the shell? Might have to happen in the jupyterhub settings.

**Comment by raspstephan** [comment]
I just set up a new VM with a GPU but would have to do all of the setup I did for the first VM manually. Maybe we should think about a way to semi-automate these processes, like creating a joint conda env, mounting the hard-drive (have to do that every time you restart the VM).

**Comment by raspstephan** [comment]
I created an environment called `nwp-downscale` from the root account. However, now it's a little dump to install packages because you have to be the root user. So you need to log into the `nwp-downscale` account and install the packages. I think we should somehow give all users permission to do this but I am tired right now :D

**Comment by HirtM** [comment]
@raspstephan Does cartopy work for you with the environment? For me it doesn't (some matplotlib deprecation error), and I have no clue what the problem is exactly. I would assume some dependencies are wrong. Maybe I'll spend some time figuring it out later, but for now I just use regular plots, no maps.

**Comment by raspstephan** [comment]
I think I also had some issues. I am so annoyed by conda and packages at the moment. See #20 

I was so annoyed I stopped working on it for a couple of days...

**Comment by raspstephan** [comment]
I will close this for now since our current "solution" seems to work at the moment even if it's not pretty.
