### ISSUE TITLE
UK data

### ISSUE THREAD

**Issue by anna-allen** [raspstephan/nwp-downscale#9]
@raspstephan, @HirtM I found met office radar and LAM data are freely available for the UK:
- Radar: https://catalogue.ceda.ac.uk/uuid/27dd6ffba67f667a18c62de5c3456350
- LAM: https://registry.opendata.aws/uk-met-office/
Could potentially be useful later to see if what we find with the US data holds for other regions 😄

**Comment by raspstephan** [comment]
Thanks for digging these up. However I believe that to access the radar dataset, we need to request access (which is of course possible).

THe LAM data, as far as I understand, only contains current forecasts, no archive. Or did I miss anything?
